name: Run bot
on:
  schedule:
    - cron: '25 21 * * *' # 21:16 UTC (2:46 AM IST)
  workflow_dispatch: # KEEP THIS for manual testing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # 1. Checkout the repository content (Updated to v4)
    - name: Checkout repo content
      uses: actions/checkout@v4 
      
    # 2. **CORRECTION:** Set up Python environment separately
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.2'
        
    - name: Install dependencies
      run: |
        pip install tweepy
        
    - name: run the bot
      run: |
        python main.py
      env:
        TWITTER_API_KEY : ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY : ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN : ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET : ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}